language: python

python:
  - "3.6"

install:
  - pip3 install pipenv
  - pipenv install fabric3

script:
  - echo $UPLOAD_ISO
  - echo $UPLOAD_LOG
  - fab helloworld

notifications:
  slack: louislabs:x4D51HjnR30LGpqZXrdbqUgB
